### ISSUE TITLE
Doesn't seem to give correct sunInSky value

### ISSUE THREAD

**Issue by Roaders** [alisdairjsmyth/node-red-contrib-sunpos#2]
Hi

I was going to write a node that did pretty much exactly what you have done here when I found your node. However, this doesn't seem to work...

With the following properties:

Latitude: 51.507351
Longitude: -0.127758
Start: Sunrise
End: Sunset start

I get the following values at 08:12 on 09 April 2016:

```
{ 
"sunInSky": false, 
"altitude": 16.681265163550602, 
"azimuth": 98.80427566135316, 
"altitudeRadians": 0.2911430005021884, 
"azimuthRadians": -1.4171327282510826 
}
```

according to [http://suncalc.net/](http://suncalc.net/) daylight today is from 06:21 to 19:44 so sunInSky should definitely be true!

**Comment by alisdairjsmyth** [comment]
Pull request changes published as 1.0.2
