### ISSUE TITLE
Wrong time period shown

### ISSUE THREAD

**Issue by Brausmith** [alisdairjsmyth/node-red-contrib-sunpos#6]
I'm not sure if I am configuring this incorrectly, but the 'day' time period doesn't seem to be accurate for the chosen lat/long. It is indeed daytime, just not with those hours.
![2018-01-06 13_24_46-microsoft edge](https://user-images.githubusercontent.com/3722950/34636057-10c6a1c0-f2e5-11e7-9fe5-18b929f496ea.png)

**Comment by alisdairjsmyth** [comment]
Can you check the locale settings?  (Specifically the timezone on the machine you have Node-Red installed on.)  It looks like Brisvegas time (based on lat,long) converted into UTC.

**Comment by Brausmith** [comment]
Thank you for the reply.
It reminded me that I might have a time sync issue between my Docker host and container. I'll update once I know more.

**Comment by Brausmith** [comment]
Noticed something a little weird tonight. Two same configured nodes on the same flow but with two different results.
![2018-01-08 19_52_42-node-red _ 10 1 1 3](https://user-images.githubusercontent.com/3722950/34665910-b5ddeb9a-f4ad-11e7-8832-7c01714835d5.png)

**Comment by alisdairjsmyth** [comment]
Odd. I am still pretty confident that this is related to locale.  You could put the following into a **function** node.  It outputs a message containing time in two formats - the locale, and UTC.  If the two are equal the locale is UTC.
 
    var now = new Date()
    var loc = now.toLocaleTimeString()
    var utc = now.toUTCString()
    msg.payload = {
        "locale": loc,
        "utc": utc
    }
    return msg

With regard the screen shot above, is it possible locale settings has been altered between execution of each node instance?

**Comment by Brausmith** [comment]
Sorry for the delay in a reply. I can confirm you are correct.
I'm not a strong Docker user, but I finally got the timezone in the container set to Australia/Brisbane and all nodes that display date and time are all now in sync.
I appreciate your patience, and I'm closing the issue.

**Comment by alisdairjsmyth** [comment]
Great!
